# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945fce90347ee3f69ec3a61c16a324e593e14dc9109285df75940d2fd2983cfc8542a7d34ddd664cd3631c9733b7f0fb086628514c4ae5aec9bde86b8ea82b2d

test:
  secret_key_base: 902258cb3e7fa61334e984e92e229451a085ee721c2def82442e3ebae7a7ff4d5e8e993dce91546e52d5a9151cc177af8c87fed0602d85533ad06def2462886c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
